services:
  sso:
    image: phenirain/fourthcoursefirstproject-sso:latest
    container_name: sso
    ports:
      - "8081:8081"
      - "7070:6060"

    networks:
      - deployments_api-network
    

networks:
  deployments_api-network:
    external: true