services:
  sso:
    image: phenirain/fourthcoursefirstproject-sso:latest
    container_name: sso
    ports:
      - "8081:8081"
      - "7070:6060"
    networks:
      - deployments_api-network

  prometheus:
    image: prom/prometheus:latest
    container_name: sso-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    networks:
      - deployments_api-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: sso-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - deployments_api-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  deployments_api-network:
    external: true

volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data: