apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P951FEA4DE68E13C5
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: sso-org
      defaultBucket: sso-metrics
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
    editable: true
