env: "dev"
connection_string: "postgres://phenirain:phenirain13%29@147.45.197.137:5432/FourthCourseFirstProject?sslmode=disable"
secret: "fourthcoursefirthproject-secret-key-256-bits-minimum-length-required-for-security"
api_address: "localhost:8080"
allowed_origins:
    - https://app.example.com
    - https://admin.example.com
    - https://phenirain.ru
    - http://phenirain.ru
    - http://localhost:3000
    - http://localhost:5173
http:
  port: 8081
  timeout: 15m
grpc: 
  admin: "api:8080"
  client: "api:8080"
  manager: "api:8080"
