global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'sso-api'
    static_configs:
      - targets: ['sso:8081']
        labels:
          service: 'sso'
          env: 'dev'
